### ISSUE TITLE
Bug: problem with projection! in jannovar-cli-033.jar

### ISSUE THREAD

**Issue by aschluter** [charite/jannovar#474]
I get an error with the following variant in hg19 assembly:

##fileformat=VCFv4.1
##contig=<ID=1,length=249250621>
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	individual
13	114435823	.	T	G	431.31	.	.	GT:AD:DP:GQ:PL	0/1:17,10:27:21:21,0,395

The error:

Options
JannovarAnnotateVCFOptions [escapeAnnField=true, pathInputVCF=ClinPrior.vcf, interval=, pathOutputVCF=outputJannovar.vcf, pathVCFDBSNP=null, prefixDBSNP=DBSNP_, pathFASTARef=null, pathVCFExac=null, prefixExac=EXAC_, pathVCFGnomadExomes=null, prefixGnomadExomes=GNOMAD_EXOMES_, pathVCFGnomadGenomes=null, prefixGnomadGenomes=GNOMAD_GENOMES_, pathVCFUK10K=null, prefixUK10K=UK10K_, pathThousandGenomes=null, prefixThousandGenomes=G1K_, pathClinVar=null, prefixClinVar=CLINVAR_, pathCosmic=null, prefixCosmic=COSMIC_, pathPedFile=null, annotateAsSingletonPedigree=false, useThresholdFilters=false, useAdvancedPedigreeFilters=false, threshFiltMinGtCovHet=8, threshFiltMinGtCovHomAlt=4, threshFiltMaxCov=10000, threshFiltMinGtGq=20, threshFiltMinGtAafHet=0.2, threshFiltMaxGtAafHet=0.8, threshFiltMinGtAafHomAlt=0.7, threshFiltMaxGtAafHomRef=0.3, threshFiltMaxExacHomAlt=20, threshFiltMaxThousandGenomesHomAlt=10, threshFiltMaxAlleleFrequencyAd=0.01, threshFiltMaxAlleleFrequencyAr=0.01, offTargetFilterEnabled=false, offTargetFilterUtrIsOffTarget=false, offTargetFilterIntronicSpliceIsOffTarget=false, oneParentGtFilteredFiltersAffected=false, inheritanceAnnoUseFilters=false, useParentGtIsFiltered=true, threshDeNovoParentAd2=1, bedAnnotationOptions=[], dbNsfpColContig=1, dbNsfpColPosition=2, prefixDbNsfp=DBNSFP_, pathDbNsfp=null, columnsDbNsfp=[], tsvAnnotationOptions=[], vcfAnnotationOptions=[]]
Deserializing transcripts...
INFO Deserializing JannovarData from C:/Users/aschluter.IDIBELL1573/Documents/R/win-library/3.6/ClinPrior/extdata/Jannovar/hg19_refseq.ser
INFO Deserialization took 7,37 sec.
Location	processed.sites	runtime.per.1M.sites	completed	total.runtime	remaining
Annotating VCF...
Will read full input file
Exception in thread "main" java.lang.Error: Bug: problem with projection!
	at de.charite.compbio.jannovar.annotation.VCFAnnotationData.setAnnoLoc(VCFAnnotationData.java:117)
	at de.charite.compbio.jannovar.annotation.Annotation.toVCFAnnoString(Annotation.java:287)
	at de.charite.compbio.jannovar.htsjdk.VariantContextAnnotator.applyAnnotations(VariantContextAnnotator.java:400)
	at de.charite.compbio.jannovar.htsjdk.VariantContextAnnotator.dispatchAnnotateVariantContext(VariantContextAnnotator.java:337)
	at de.charite.compbio.jannovar.htsjdk.VariantContextAnnotator.annotateVariantContext(VariantContextAnnotator.java:296)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Iterator.forEachRemaining(Unknown Source)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachOrdered(Unknown Source)
	at de.charite.compbio.jannovar.cmd.annotate_vcf.AnnotateVCFCommand.run(AnnotateVCFCommand.java:411)
	at de.charite.compbio.jannovar.Jannovar.main(Jannovar.java:67)
Caused by: de.charite.compbio.jannovar.reference.ProjectionException: Invalid transcript sequence position 1302
	at de.charite.compbio.jannovar.reference.TranscriptProjectionDecorator.transcriptToGenomePos(TranscriptProjectionDecorator.java:169)
	at de.charite.compbio.jannovar.annotation.VCFAnnotationData.setAnnoLoc(VCFAnnotationData.java:113)
	... 15 more
[1] 1

**Comment by aschluter** [comment]
It seems that is a problem with the hg19_refseq.ser file. When I annotate with the hg19_ucsc.ser the error disappears. This variant is out of range in Hg38 assembly but not in Hg19.

**Comment by visze** [comment]
I get she same error on another VCF file (have to find the mutation which causes it). It is also refseq and hg19.

```
Exception in thread "main" java.lang.Error: Bug: problem with projection!
        at de.charite.compbio.jannovar.annotation.VCFAnnotationData.setAnnoLoc(VCFAnnotationData.java:117)
        at de.charite.compbio.jannovar.annotation.Annotation.toVCFAnnoString(Annotation.java:287)
        at de.charite.compbio.jannovar.htsjdk.VariantContextAnnotator.applyAnnotations(VariantContextAnnotator.java:400)
        at de.charite.compbio.jannovar.htsjdk.VariantContextAnnotator.dispatchAnnotateVariantContext(VariantContextAnnotator.java:337)
        at de.charite.compbio.jannovar.htsjdk.VariantContextAnnotator.annotateVariantContext(VariantContextAnnotator.java:296)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:423)
        at de.charite.compbio.jannovar.cmd.annotate_vcf.AnnotateVCFCommand.run(AnnotateVCFCommand.java:411)
        at de.charite.compbio.jannovar.Jannovar.main(Jannovar.java:67)
Caused by: de.charite.compbio.jannovar.reference.ProjectionException: Invalid transcript sequence position 362
        at de.charite.compbio.jannovar.reference.TranscriptProjectionDecorator.transcriptToGenomePos(TranscriptProjectionDecorator.java:169)
        at de.charite.compbio.jannovar.annotation.VCFAnnotationData.setAnnoLoc(VCFAnnotationData.java:113)

```

@holtgrewe any suggetsions?

**Comment by visze** [comment]
it is wired. it only appears when using VCF file as intup. NOT if yousing `annotate-pos`

**Comment by holtgrewe** [comment]
Hm, somehow we get a transcript position outside of the transcripts...

**Comment by holtgrewe** [comment]
About 65 genes are affected but I think I know how to fix it.

```
      2 NM_000451.3
      2 NM_001012288.1
      2 NM_001017915.1
      2 NM_001039350.1
      2 NM_001077693.2
      2 NM_001099289.1
      2 NM_001113239.2
      2 NM_001122636.1
      2 NM_001122898.1
      2 NM_001145149.2
      2 NM_001161529.1
      2 NM_001161530.1
      2 NM_001161531.1
      2 NM_001161532.1
      2 NM_001170637.2
      2 NM_001171038.1
      2 NM_001171039.1
      2 NM_001171135.1
      2 NM_001171136.1
      2 NM_001173473.1
      2 NM_001173474.1
      2 NM_001185183.1
      2 NM_001220765.1
      2 NM_001220766.1
      2 NM_001220767.1
      2 NM_001220768.1
      2 NM_001220769.1
      2 NM_001220770.1
      2 NM_001220771.1
      2 NM_001267713.1
      2 NM_001271872.1
      2 NM_001271893.1
      2 NM_001277710.1
      2 NM_001636.3
      2 NM_001733.4
      2 NM_001936.3
      2 NM_002183.3
      2 NM_002186.2
      2 NM_002414.3
      2 NM_002929.2
      2 NM_004043.2
      2 NM_004192.3
      2 NM_004522.2
      2 NM_004729.3
      2 NM_005088.2
      2 NM_005541.3
      2 NM_005638.5
      2 NM_005840.1
      2 NM_006060.4
      2 NM_006140.4
      2 NM_006883.2
      2 NM_012227.2
      2 NM_013239.4
      2 NM_014938.4
      2 NM_015326.3
      2 NM_018390.3
      2 NM_022148.2
      2 NM_022740.4
      2 NM_130797.2
      2 NM_145177.2
      2 NM_172245.2
      2 NM_172246.2
      2 NM_172247.2
      2 NM_172249.2
      2 NM_173471.3
      2 NM_176786.1
      2 NM_178129.4
```

**Comment by holtgrewe** [comment]
```
95 int projectedTranscriptPos = transcript.getSeqAlignment().projectRefToQry(transcriptPos);
```

**Comment by holtgrewe** [comment]
OK, the problem appears to be in the projection for the transcript location (that falls out of the transcript), here in the case of long leading gaps. However, this is not actually used downstream anyway... Let me have another good look how to fix it.

**Comment by holtgrewe** [comment]
Fixed in #477.

**Comment by visze** [comment]
Works now for me in the new version!

**Comment by aschluter** [comment]
Thanks for the fix. It works fine for Chr13:114435823 but I still have problems now for this variant (same error using updated hg19_refseq.ser):
1	148251986	rs199949374	T	G	2803.33	.	.	GT:AD:DP:GQ:PL	0/1:124,108:232:99:2816,0,3317

Exception in thread "main" java.lang.Error: Bug: problem with projection!
	at de.charite.compbio.jannovar.annotation.VCFAnnotationData.setAnnoLoc(VCFAnnotationData.java:117)
	at de.charite.compbio.jannovar.annotation.Annotation.toVCFAnnoString(Annotation.java:287)
	at de.charite.compbio.jannovar.htsjdk.VariantContextAnnotator.applyAnnotations(VariantContextAnnotator.java:400)
	at de.charite.compbio.jannovar.htsjdk.VariantContextAnnotator.dispatchAnnotateVariantContext(VariantContextAnnotator.java:337)
	at de.charite.compbio.jannovar.htsjdk.VariantContextAnnotator.annotateVariantContext(VariantContextAnnotator.java:296)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Iterator.forEachRemaining(Unknown Source)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachOrdered(Unknown Source)
	at de.charite.compbio.jannovar.cmd.annotate_vcf.AnnotateVCFCommand.run(AnnotateVCFCommand.java:411)
	at de.charite.compbio.jannovar.Jannovar.main(Jannovar.java:67)
Caused by: de.charite.compbio.jannovar.reference.ProjectionException: Invalid transcript sequence position 15755
	at de.charite.compbio.jannovar.reference.TranscriptProjectionDecorator.transcriptToGenomePos(TranscriptProjectionDecorator.java:170)
	at de.charite.compbio.jannovar.annotation.VCFAnnotationData.setAnnoLoc(VCFAnnotationData.java:113)
	... 15 more
[

**Comment by visze** [comment]
Thank you for reporting! We have to dig deeper. it was not so easy to fix the previous issue and maybe we missed something.

**Comment by smw1414** [comment]
Hi, 
We also found the similar issue with position of chr19:17402940C>A(rs2245519) hg38 in version 34. Could you check this issue, thank you.

**Comment by smw1414** [comment]
Hi, we found two positions with the same issue using jannovar-0.35. The database is hg38_refseq_curated
chrX    49069802        .       C       A 
chrX    49069814        .       C       A

**Comment by smw1414** [comment]
Hi,  I have tried to use https://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/annotation/annotation_releases/109/GCF_000001405.38_GRCh38.p12 for the database building, but it still caused the same issue. 
However, GRCh38.p13 (109.20200815) could somehow temporarily solve this issue. Hope this could help

**Comment by holtgrewe** [comment]
**First Variant**

>  `1 148251986 rs199949374 T G 2803.33 . . GT:AD:DP:GQ:PL 0/1:124,108:232:99:2816,0,3317`

This appears to work at least with the current `develop` and the `hg19_refseq.ser` that is in the ZIP attached to the v34 release.

```
# java -jar jannovar-cli/target/jannovar-cli-0.36-SNAPSHOT.jar annotate-pos -d ~/Downloads/hg19_refseq.ser -c 'chr1:148251986T>G'
Options
JannovarAnnotatePosOptions [genomicChanges=[chr1:148251986T>G], toString()=JannovarAnnotationOptions [useThreeLetterAminoAcidCode=false, nt3PrimeShifting=false, showAll=false, databaseFilePath=C:/Users/mholtgre/Downloads/hg19_refseq.ser, toString()=JannovarBaseOptions [reportProgress=true, httpProxy=null, httpsProxy=null, ftpProxy=null, verbosity=1]]]
Deserializing transcripts...
INFO Deserializing JannovarData from C:/Users/mholtgre/Downloads/hg19_refseq.ser
INFO Deserialization took 9.55 sec.
#change effect  hgvs_annotation messages
chr1:148251986T>G       SYNONYMOUS_VARIANT      NBPF20:NM_001278267.1:c.14556G>C:p.(=)  WARNING_REF_DOES_NOT_MATCH_TRANSCRIPT
```

However, VariantValidator has problems with this transcript...

**Second Variant**

> ` chrX 49069802 . C A`

```
# java -jar jannovar-cli/target/jannovar-cli-0.36-SNAPSHOT.jar annotate-pos -d ~/Downloads/hg38_refseq_curated.ser -c 'chrX:49069802C>A'
Options
JannovarAnnotatePosOptions [genomicChanges=[chrX:49069802C>A], toString()=JannovarAnnotationOptions [useThreeLetterAminoAcidCode=false, nt3PrimeShifting=false, showAll=false, databaseFilePath=C:/Users/mholtgre/Downloads/hg38_refseq_curated.ser, toString()=JannovarBaseOptions [reportProgress=true, httpProxy=null, httpsProxy=null, ftpProxy=null, verbosity=1]]]
Deserializing transcripts...
INFO Deserializing JannovarData from C:/Users/mholtgre/Downloads/hg38_refseq_curated.ser
INFO Deserialization took 6.77 sec.
#change effect  hgvs_annotation messages
chrX:49069802C>A        THREE_PRIME_UTR_EXON_VARIANT    CCDC120:NM_001163321.2:c.*1260C>A:p.(=) .
```

Also here, VariantValidator does not like the variant: `No transcripts found that fully overlap the described variation in the genomic sequence`

I think that we need to rework the way how the transcript databases are built and provide centrally built ones. I have the suspicion that problems with the variants come from home-built databases. I'll try some more variants, though.

**Comment by holtgrewe** [comment]
```
$java -jar jannovar-cli/target/jannovar-cli-0.36-SNAPSHOT.jar annotate-pos -d ~/Downloads/hg38_refseq_curated.ser -c 'chr19:17402940C>A'
Options
JannovarAnnotatePosOptions [genomicChanges=[chr19:17402940C>A], toString()=JannovarAnnotationOptions [useThreeLetterAminoAcidCode=false, nt3PrimeShifting=false, showAll=false, databaseFilePath=C:/Users/mholtgre/Downloads/hg38_refseq_curated.ser, toString()=JannovarBaseOptions [reportProgress=true, httpProxy=null, httpsProxy=null, ftpProxy=null, verbosity=1]]]
Deserializing transcripts...
INFO Deserializing JannovarData from C:/Users/mholtgre/Downloads/hg38_refseq_curated.ser
INFO Deserialization took 8.26 sec.
#change effect  hgvs_annotation messages
chr19:17402940C>A       THREE_PRIME_UTR_EXON_VARIANT    BST2:NM_004335.3:c.*402G>T:p.(=)        .
```

**Comment by holtgrewe** [comment]
Please re-open if you think that the problem persists.

**Comment by smw1414** [comment]
Hi , 
You should try with "--show-all ", then you can find the problem still existed. 
```
 java -jar jannovar-cli/target/jannovar-cli-0.36-SNAPSHOT.jar annotate-pos -d ~/Downloads/hg38_refseq_curated.ser -c 'chrX:49069802C>A' --show-all 
```
For the variants (chrX:49069802C>A; chrX:49069814C>A) I  reported is something to do with the inconsistency between RefSeq transcript sequences and hg38 sequences.  
Without the "show-all", the jannovar gives the annotation of NM_001163321. This transcript sequence is consistent with hg38.
https://genome.ucsc.edu/cgi-bin/hgc?hgsid=1089526707_Nela6HllnMAp79RHfI0A52gzhqBG&g=htcCdnaAli&i=NM_001163321.4&c=chrX&l=49058998&r=49069854&o=49058998&aliTable=ncbiRefSeqPsl
![圖片](https://user-images.githubusercontent.com/28624336/121268284-37df0100-c8f0-11eb-9d9e-7f53b6e479a0.png)

While with the "show-all",  the jannovar gives some other transcripts and returns an error.  
Here is the one of the examples.  The sequence in black indicate that this transcript sequence is inconsistent with hg38.   
https://genome.ucsc.edu/cgi-bin/hgc?hgsid=1089526707_Nela6HllnMAp79RHfI0A52gzhqBG&g=htcCdnaAli&i=NM_001271836.2&c=chrX&l=49053571&r=49069854&o=49053571&aliTable=ncbiRefSeqPsl   
![圖片](https://user-images.githubusercontent.com/28624336/121268884-64474d00-c8f1-11eb-842d-9540e0ab05d8.png)

I checked the ensemble transcript but no such issue. So I made some modifications.    
For the CDNA sequence (fna) file, I manually modified those inconsistent transcripts sequences to match with hg38, and removed the "CDNA_match" records of hg38-inconsistent transcripts from the gff file.

**Comment by holtgrewe** [comment]
Hi, thanks for the message.

First, let's have a look at the variant databases involved. You are using `hg38_refseq_curated`. This means it's based on the GRCh38 release with the refseq database and only uses the `NM_` records which are curated from genbank sequences (actual observations) rather than `XM_` records which are based on gene prediction software. You are referecing UCSC genome browser which to the best of my knowledge their own RefSeq sequence alignments and maybe different versions of transcripts. There are a couple of interesting slide decks by Reece Hart with regards to how tricky transcript alignments can be, e.g., [this one](https://www.slideshare.net/variomeproj/the-clinical-significance-of-transcript-alignment-discrepancies-and-tools-to-help-you-deal-with-them-reece-hart).

Second, let us see what Jannovar returns (it would have been helpful to see your full output as well). For comparison the MD5 checkusm of my `hg38_refseq_curated.ser` file is `de4777d32470517aa38819b8b513aef1`.

```
# java -jar jannovar-cli/target/jannovar-cli-0.36-SNAPSHOT.jar annotate-pos -d ~/Downloads/hg38_refseq_curated.ser  -c 'chrX:49069802C>A' --show-all
Options
JannovarAnnotatePosOptions [genomicChanges=[chrX:49069802C>A], toString()=JannovarAnnotationOptions [useThreeLetterAminoAcidCode=false, nt3PrimeShifting=false, showAll=true, databaseFilePath=C:/Users/mholtgre/Downloads/hg38_refseq_curated.ser, toString()=JannovarBaseOptions [reportProgress=true, httpProxy=null, httpsProxy=null, ftpProxy=null, verbosity=1]]]
Deserializing transcripts...
INFO Deserializing JannovarData from C:/Users/mholtgre/Downloads/hg38_refseq_curated.ser
INFO Deserialization took 7.22 sec.
#change effect  hgvs_annotation messages
chrX:49069802C>A        THREE_PRIME_UTR_EXON_VARIANT,THREE_PRIME_UTR_EXON_VARIANT,THREE_PRIME_UTR_EXON_VARIANT,THREE_PRIME_UTR_EXON_VARIANT,THREE_PRIME_UTR_EXON_VARIANT,THREE_PRIME_UTR_EXON_VARIANT       CCDC120:NM_001163321.2:c.*1260C>A:p.(=),CCDC120:NM_001163322.2:c.*1260C>A:p.(=),CCDC120:NM_001163323.2:c.*1806C>A:p.(=),CCDC120:NM_001271835.1:c.*1806C>A:p.(=),CCDC120:NM_001271836.1:c.*1806C>A:p.(=),CCDC120:NM_033626.3:c.*1806C>A:p.(=)        .;.;.;.;.;.
```

```
# java -jar jannovar-cli/target/jannovar-cli-0.36-SNAPSHOT.jar annotate-pos -d ~/Downloads/hg38_refseq_curated.ser  -c 'chrX:49069814C>A' --show-all
Options
JannovarAnnotatePosOptions [genomicChanges=[chrX:49069814C>A], toString()=JannovarAnnotationOptions [useThreeLetterAminoAcidCode=false, nt3PrimeShifting=false, showAll=true, databaseFilePath=C:/Users/mholtgre/Downloads/hg38_refseq_curated.ser, toString()=JannovarBaseOptions [reportProgress=true, httpProxy=null, httpsProxy=null, ftpProxy=null, verbosity=1]]]
Deserializing transcripts...
INFO Deserializing JannovarData from C:/Users/mholtgre/Downloads/hg38_refseq_curated.ser
INFO Deserialization took 7.57 sec.
#change effect  hgvs_annotation messages
chrX:49069814C>A        THREE_PRIME_UTR_EXON_VARIANT,THREE_PRIME_UTR_EXON_VARIANT,THREE_PRIME_UTR_EXON_VARIANT,THREE_PRIME_UTR_EXON_VARIANT,THREE_PRIME_UTR_EXON_VARIANT,THREE_PRIME_UTR_EXON_VARIANT       CCDC120:NM_001163321.2:c.*1272C>A:p.(=),CCDC120:NM_001163322.2:c.*1272C>A:p.(=),CCDC120:NM_001163323.2:c.*1818C>A:p.(=),CCDC120:NM_001271835.1:c.*1818C>A:p.(=),CCDC120:NM_001271836.1:c.*1818C>A:p.(=),CCDC120:NM_033626.3:c.*1818C>A:p.(=)        .;.;.;.;.;.
```

So we don't see an error here...

Third, let us see what variant validator says. Variant Validator is the most advanced tool for mapping between different coordinate systems (genomes, transcripts, and others). I would interpret VV as **the** reference.

For the first:

![image](https://user-images.githubusercontent.com/521780/121299555-e5a0de80-c8f5-11eb-9d02-a705254d0fee.png)

For the second:

![image](https://user-images.githubusercontent.com/521780/121299589-f0f40a00-c8f5-11eb-98af-014a6cc0debd.png)

-- which is kind of weird.

Now, looking at the first locus in NCBI genome viewer. Here it looks like 3' end is the correct prediction.

![image](https://user-images.githubusercontent.com/521780/121299960-711a6f80-c8f6-11eb-8f1f-5e1362b06d74.png)

Please double-check, what Jannovar tells you. You can find the `.ser` file that I used here at Zenodo.

- https://zenodo.org/record/4906580#.YMBVckyxUaE

In the case that you want to share your `.ser` file then you can append it to a ticket if you make it a ZIP file.

Please re-open in the case that the problem persists.

**Comment by smw1414** [comment]
Hi, 
I found that use annotate-pos does not return an error. However, the annotate-vcf returned an error. I also used the ser file you provided, but it didn't solve the problem.  Here's the log.
```
# md5sum 0.34_ser/hg38_refseq_curated.ser
de4777d32470517aa38819b8b513aef1  0.34_ser/hg38_refseq_curated.ser

# java -jar jannovar-cli-0.35.jar  annotate-vcf  -d 0.34_ser/hg38_refseq_curated.ser -i bug1.vcf -o tmp.vcf --show-all
Options
JannovarAnnotateVCFOptions [escapeAnnField=true, pathInputVCF=bug1.vcf, interval=, pathOutputVCF=tmp.vcf, pathVCFDBSNP=null, prefixDBSNP=DBSNP_, pathFASTARef=null, pathVCFExac=null, prefixExac=EXAC_, pathVCFGnomadExomes=null, prefixGnomadExomes=GNOMAD_EXOMES_, pathVCFGnomadGenomes=null, prefixGnomadGenomes=GNOMAD_GENOMES_, pathVCFUK10K=null, prefixUK10K=UK10K_, pathThousandGenomes=null, prefixThousandGenomes=G1K_, pathClinVar=null, prefixClinVar=CLINVAR_, pathCosmic=null, prefixCosmic=COSMIC_, pathPedFile=null, annotateAsSingletonPedigree=false, useThresholdFilters=false, useAdvancedPedigreeFilters=false, threshFiltMinGtCovHet=8, threshFiltMinGtCovHomAlt=4, threshFiltMaxCov=10000, threshFiltMinGtGq=20, threshFiltMinGtAafHet=0.2, threshFiltMaxGtAafHet=0.8, threshFiltMinGtAafHomAlt=0.7, threshFiltMaxGtAafHomRef=0.3, threshFiltMaxExacHomAlt=20, threshFiltMaxThousandGenomesHomAlt=10, threshFiltMaxAlleleFrequencyAd=0.01, threshFiltMaxAlleleFrequencyAr=0.01, offTargetFilterEnabled=false, offTargetFilterUtrIsOffTarget=false, offTargetFilterIntronicSpliceIsOffTarget=false, oneParentGtFilteredFiltersAffected=false, inheritanceAnnoUseFilters=false, useParentGtIsFiltered=true, threshDeNovoParentAd2=1, bedAnnotationOptions=[], dbNsfpColContig=1, dbNsfpColPosition=2, prefixDbNsfp=DBNSFP_, pathDbNsfp=null, columnsDbNsfp=[], tsvAnnotationOptions=[], vcfAnnotationOptions=[]]
Deserializing transcripts...
INFO Deserializing JannovarData from 0.34_ser/hg38_refseq_curated.ser
INFO Deserialization took 6.33 sec.
Location        processed.sites runtime.per.1M.sites    completed       total.runtime   remaining
Annotating VCF...
Will read full input file
Exception in thread "main" java.lang.Error: Bug: problem with projection!
        at de.charite.compbio.jannovar.annotation.VCFAnnotationData.setAnnoLoc(VCFAnnotationData.java:117)
        at de.charite.compbio.jannovar.annotation.Annotation.toVCFAnnoString(Annotation.java:287)
        at de.charite.compbio.jannovar.htsjdk.VariantContextAnnotator.applyAnnotations(VariantContextAnnotator.java:400)
        at de.charite.compbio.jannovar.htsjdk.VariantContextAnnotator.dispatchAnnotateVariantContext(VariantContextAnnotator.java:337)
        at de.charite.compbio.jannovar.htsjdk.VariantContextAnnotator.annotateVariantContext(VariantContextAnnotator.java:296)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:502)
        at de.charite.compbio.jannovar.cmd.annotate_vcf.AnnotateVCFCommand.run(AnnotateVCFCommand.java:411)
        at de.charite.compbio.jannovar.Jannovar.main(Jannovar.java:67)
Caused by: de.charite.compbio.jannovar.reference.ProjectionException: Invalid transcript sequence position 3597
        at de.charite.compbio.jannovar.reference.TranscriptProjectionDecorator.transcriptToGenomePos(TranscriptProjectionDecorator.java:170)
        at de.charite.compbio.jannovar.annotation.VCFAnnotationData.setAnnoLoc(VCFAnnotationData.java:113)
        ... 15 more

  
```
[problematic_position.zip](https://github.com/charite/jannovar/files/6623646/problematic_position.zip)

I attached the vcf file that I used.  The position is different, but they locate at the same region and cause the same error.

**Comment by holtgrewe** [comment]
@smw1414 thanks for bearing with us... I'm currently looking into #524 which probably is related

**Comment by holtgrewe** [comment]
I think I fixed it in branch `524-dbsnp-projection-hg38`. At least your `bug{1,2}.vcf` work now.

**Comment by holtgrewe** [comment]
I will let jannovar run through dbsnp for GRCh37 and GRCh38 and both ensembl and refseq transcripts. If this succeeds then I will merge #525 and make a new Jannovar release.

**Comment by holtgrewe** [comment]
OK, #525 runs through on dbSNP.
